
-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBE COMO PARAMETRO
-- UN CODIGO DE ASIGNATURA (CAS) Y MUESTRA POR PANTALLA
-- EL CODIGO DE AREA Y EL NOMBRE DEL AREA A LA QUE PERTENECE
-- EL CODIGO DEL DEPARTAMENTO Y EL NOMBRE DEL DEPARTAMENTO A LA QUE PERTENECE

SET SERVEROUTPUT ON;
CREATE PROCEDURE P4(v_as ASIGNATURA.CAS%TYPE)
IS
    -- CURSOR PARA ALMACENAR EL CODIGO DEL DEPARTAMENTO Y EL NOMBRE DEL MISMO
    CURSOR dept
    IS
        SELECT CD,D
        FROM DEPARTAMENTO NATURAL JOIN AREA
        WHERE AR = (SELECT AR
                    FROM ASIGNATURA
                    WHERE CAS = v_as);
        
    -- CURSOR PARA ALMANECENAR EL CODIGO DE AREA Y EL NOMBRE DE ESA AREA            
    CURSOR are
    IS
        SELECT CAR,AR
        FROM AREA NATURAL JOIN ASIGNATURA
        WHERE CAS = v_as;
    
    -- VARIABLES UTILZADAS PARA RESCATAR LOS VALORES
    v_cd DEPARTAMENTO.CD%TYPE;
    v_d  DEPARTAMENTO.D%TYPE;
    
    v_car AREA.CAR%TYPE;
    v_ar  AREA.AR%TYPE;
    
BEGIN

    -- ABRIMOS LOS DOS CURSORES
    OPEN dept; 
    OPEN are;
        -- RESCATAMOS LOS VALORES QUE SE HAN ALMACENADO
        FETCH dept INTO v_cd,v_d;
        FETCH are  INTO v_car,v_ar;
    -- CERRAMOS LOS CURSORES
    CLOSE dept;
    CLOSE are;
    -- MOSTRAMOS EL RESULTADO
    DBMS_OUTPUT.PUT_LINE('LA ASIGNATURA CON CODIGO: '||v_as||' ESTA ADSCRITA AL AREA: '||v_ar||' ('||v_car||') QUE PERTENECE AL DEPARTAMENTO: '||v_d||' ('||v_cd||')');
END;    