
--
-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBA COMO ARGUMENTO 
-- UN CODIGO DE DEPARTAMENTO (CD) Y MUESTRE POR PANTALLA 
-- LOS NOMBRES DE LAS ÁREAS DE CONOCIMIENTO ADSCRITAS AL MISMO.
--

SET SERVEROUTPUT ON;
CREATE PROCEDURE P1(v_cd DEPARTAMENTO.CD%TYPE)
IS
  v_num NUMBER;
BEGIN
SELECT COUNT(*)
INTO v_num
FROM DEPARTAMENTO NATURAL JOIN AREA
WHERE CD=v_cd;
DBMS_OUTPUT.PUT_LINE('EL NUMERO DE AREAS DEL DEPARTAMENTO CON CD= '||v_cd||' ES: '||v_num);
END;
