
--
-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBA COMO ARGUMENTO 
-- UN CODIGO DE DEPARTAMENTO (CD) Y MUESTRE POR PANTALLA 
-- LOS NOMBRES DE LAS ÁREAS DE CONOCIMIENTO ADSCRITAS AL MISMO.
--


CREATE PROCEDURE P1(v_cd DEPARTAMENTO.CD%TYPE)
IS
  CURSOR c_area IS
    SELECT AR
    FROM DEPARTAMENTO NATURAL JOIN AREA
    WHERE CD = v_cd;
    
    v_area AREA.AR%TYPE;
    
BEGIN
    OPEN c_area;
    LOOP
        FETCH c_area INTO v_area;
            EXIT WHEN c_area%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(v_area);
    END LOOP;
END;