

-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBE COMO PARÁMETRO
-- UN CODIGO DE DEPARTAMENTO (CD) Y LISTA LOS NOMBRES DE
-- LOS PROFESORES QUE PERTENECEN A ESE DEPARTAMENTO

SERVEROUTPUT ON;
CREATE PROCEDURE P2 (v_cd DEPARTAMENTO.CD%TYPE)
IS
    CURSOR profesores
    IS
    SELECT P
    FROM PROFESOR NATURAL JOIN AREA
    WHERE CD = v_cd;
    
    v_p PROFESOR.P%TYPE;
    v_d DEPARTAMENTO.D%TYPE;

BEGIN
    SELECT D
    INTO v_d
    FROM DEPARTAMENTO
    WHERE CD = v_cd;
    
    DBMS_OUTPUT.PUT_LINE(v_d);
    
    OPEN profesores;
    LOOP
        FETCH profesores INTO v_p;
        EXIT WHEN profesores%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(v_p);
    END LOOP;
END;