

-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBA COMO PARÁMETRO UN CAS
-- Y MUESTRE LOS PROFESORES QUE HAN IMPARTIDO ESA ASIGNATURA

SET SERVEROUTPUT ON;

CREATE PROCEDURE P1 (v_as ASIGNATURA.CAS%TYPE)
IS
    CURSOR profesores
    IS
        SELECT UNIQUE P
        FROM PROFESOR NATURAL JOIN PLAN_DOCENTE
        WHERE CAS = v_as;
    
    v_p PROFESOR.P%TYPE;

BEGIN

    OPEN profesores;
    LOOP
        FETCH profesores INTO v_p;
        EXIT WHEN profesores%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE (v_p);
    END LOOP;
    CLOSE profesores;
END;