

DECLARE
	v_t TITULACION.T%TYPE;
	v_f TITULACION.FAC%TYPE;
	
BEGIN
	SELECT T,FAC
	INTO v_t,v_f
	FROM TITULACION
	WHERE T = (SELECT T
			   FROM ASIGNATURA
		       GROUP BY T
		   	   HAVING COUNT(UNIQUE CAS) = (SELECT MAX(COUNT(UNIQUE CAS))
			   							    FROM ASIGNATURA
									   		GROUP BY T));
		DBMS_OUTPUT.PUT_LINE(v_t || '  '||v_f);
	END;
