
-- CREAR UN PROCEDIMIENTO PL/SQL QUE RECIBE COMO PARAMETRO
-- UN CODIGO DE ASIGNATURA Y DEVUELVE EL NOMBRE DE LA ASIGNATURA
-- Y LA CANTIDAD TOTAL DE CREDITOS QUE TIENE LA MISMA

SET SERVEROUTPUT ON;
CREATE PROCEDURE P3(v_as ASIGNATURA.CAS%TYPE)
IS
    v_a ASIGNATURA.A%TYPE;
    v_c NUMBER;

BEGIN
    SELECT A
    INTO v_a
    FROM ASIGNATURA
    WHERE CAS = v_as;
    
    SELECT CT+CP+CL 
    INTO v_c
    FROM ASIGNATURA
    WHERE CAS = v_as;
    
    DBMS_OUTPUT.PUT_LINE('LA ASIGNATURA: ' ||v_a||' TIENE EN TOTAL '||v_c||' CRÉDITOS');
END;